Write-Host "Reloading VS Code Configuration for Maven Project..."
Write-Host "1. Please ensure you have installed the following VS Code extensions:"
Write-Host "   - vscjava.vscode-java-pack"
Write-Host "   - vmware.vscode-spring-boot"
Write-Host "   - redhat.vscode-xml"
Write-Host "   - vscjava.vscode-maven"
Write-Host "2. Close and reopen VS Code"
Write-Host "3. Run the Maven build task using Ctrl+Shift+B"
Write-Host "4. Run the Spring Boot application using F5"
Write-Host ""
Write-Host "If you still have issues, run this command in the terminal:"
Write-Host "mvn clean package"
Write-Host "java -jar target\\workforcemgmt-0.0.1-SNAPSHOT.jar"
